apiVersion: v1
kind: Secret
metadata:
  name: payments
  namespace: roboshop
type: Opaque
data:
  AMQP_USER: cm9ib3Nob3A=
  AMQP_PASS: cm9ib3Nob3AxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: roboshop
  labels: # these labels are deployment labels
    app: payments
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: payments
      project: roboshop
      tier: app
  template:
    metadata:
      labels: # these labels are pod labels
        app: payments
        project: roboshop
        tier: app
    spec:
      containers:
      - name: payments
        image: "{{ .Values.deployment.imageURL }}:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: payments
        env:    
          - name: AMQP_HOST
            valueFrom:
              secretKeyRef:
                name: rabbitmq 
                key: AMQP_HOST   
---
apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: roboshop
spec:
  selector:
    app: payments
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port